export default {
  GET_EVENTS_REQUEST: "GET_EVENTS_REQUEST",
  GET_EVENTS_SUCCESS: "GET_EVENTS_SUCCESS",
  GET_EVENTS_ERROR: "GET_EVENTS_ERROR",

  GET_TAGS_REQUEST: "GET_TAGS_REQUEST",
  GET_TAGS_SUCCESS: "GET_TAGS_SUCCESS",
  GET_TAGS_ERROR: "GET_TAGS_ERROR",

  GET_SURVEYS_REQUEST: "GET_SURVEYS_REQUEST",
  GET_SURVEYS_SUCCESS: "GET_SURVEYS_SUCCESS",
  GET_SURVEYS_ERROR: "GET_SURVEYS_ERROR",

  UPDATE_EVENT_REQUEST: "UPDATE_EVENT_REQUEST",
  UPDATE_EVENT_SUCCESS: "UPDATE_EVENT_SUCCESS",
  UPDATE_EVENT_ERROR: "UPDATE_EVENT_ERROR",

  UPDATE_TAGS_REQUEST: "UPDATE_TAGS_REQUEST",
  UPDATE_TAGS_SUCCESS: "UPDATE_TAGS_SUCCESS",
  UPDATE_TAGS_ERROR: "UPDATE_TAGS_ERROR",

  UPDATE_SURVEY_REQUEST: "UPDATE_SURVEY_REQUEST",
  UPDATE_SURVEY_SUCCESS: "UPDATE_SURVEY_SUCCESS",
  UPDATE_SURVEY_ERROR: "UPDATE_SURVEY_ERROR",

  SET_SURVEY_IMAGE: "SET_SURVEY_IMAGE",
};
