export default {
  LOCAL_STORAGE_LOG_IN_EMAIL: "LOCAL_STORAGE_LOG_IN_EMAIL",
  FIRESTORE_QUESTIONS_COLLECTION: "questions",
  SURVEY_MAX_QUESTIONS: 20,
  SURVEY_MAX_CHOICES: 6,
  SURVEY_QUESTION_TYPE_TEXT: "input-text",
  SURVEY_QUESTION_TYPE_SINGLE: "single-choice",
  SURVEY_QUESTION_TYPE_MULTIPLE: "multiple-choice",
};
